debian/conf/* etc/nginx
debian/NEWS.Debian usr/share/doc/nginx
debian/ufw.profile etc/ufw/applications.d/nginx
debian/build-extras/objs/nginx usr/sbin
html/* usr/share/nginx/www/
debian/build-extras/objs/src/http/modules/perl/blib/arch/auto/nginx/nginx.so usr/lib/perl5/auto/nginx
debian/build-extras/objs/src/http/modules/perl/blib/arch/auto/nginx/nginx.bs usr/lib/perl5/auto/nginx
debian/build-extras/objs/src/http/modules/perl/blib/lib/nginx.pm usr/lib/perl5
